# ***This notebook is only for testing***

In [1]:
from matrix import Matrix
import time


In [2]:
x = Matrix([[1,2,1],[0,1,0],[2,3,4]])
y = Matrix([[2,5],[6,7],[1,8]])

In [3]:
%%time
z = x @ y

CPU times: user 25 µs, sys: 12 µs, total: 37 µs
Wall time: 40.3 µs


In [4]:
print(z.numpy())

[[15 27]
 [ 6  7]
 [26 63]]


In [5]:
test = [
  [1,2,3,0],
  [4,5,6,1],
  [4,5,6,1],
  [7,8,9,2]
]

matrix = Matrix(test)

In [6]:
matrix

<'Matrix' object at 0x7f32d22dbac0 size=16 shape=(4, 4) symbol=None>

In [7]:
matrix.max_pooling((2,2)).numpy()

array([[5, 6, 6],
       [5, 6, 6],
       [8, 9, 9]])

In [8]:
%%time
matrix.argmax()

CPU times: user 15 µs, sys: 7 µs, total: 22 µs
Wall time: 24.6 µs


9

In [9]:
%%time
matrix.argmin()

CPU times: user 5 µs, sys: 2 µs, total: 7 µs
Wall time: 10.7 µs


0

In [10]:
from matrix import identity

In [11]:
identity(3).numpy()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
matrix.rand_like()

<'Matrix' object at 0x7f32d22da380 size=16 shape=(4, 4) symbol=None>

In [13]:
matrix.zeros_like().numpy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
matrix.ones_like().numpy()

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
from torch import Tensor
import torch

In [16]:
x = Tensor([[1,2,3],[3,4,5],[6,7,8]])
y = Tensor([[1,4,9],[9,16,25],[36,49,64]])

In [17]:
z = torch.stack((x,y),dim = 0)

In [18]:
z

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 1.,  4.,  9.],
         [ 9., 16., 25.],
         [36., 49., 64.]]])

In [19]:
a = torch.stack((x,y),dim = 1)

In [20]:
a

tensor([[[ 1.,  2.,  3.],
         [ 1.,  4.,  9.]],

        [[ 3.,  4.,  5.],
         [ 9., 16., 25.]],

        [[ 6.,  7.,  8.],
         [36., 49., 64.]]])

In [21]:
p = torch.hstack((x,y))
p

tensor([[ 1.,  2.,  3.,  1.,  4.,  9.],
        [ 3.,  4.,  5.,  9., 16., 25.],
        [ 6.,  7.,  8., 36., 49., 64.]])

In [22]:
q = torch.vstack((x,y))
q

tensor([[ 1.,  2.,  3.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 1.,  4.,  9.],
        [ 9., 16., 25.],
        [36., 49., 64.]])

In [23]:
t1 = Tensor([[1,2],[3,4],[5,6]])
t2 = Tensor([[1,4],[9,16],[25,36]])
torch.vstack((t1,t2))

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])

In [24]:
torch.hstack((t1,t2))

tensor([[ 1.,  2.,  1.,  4.],
        [ 3.,  4.,  9., 16.],
        [ 5.,  6., 25., 36.]])

In [25]:
mat1 = Matrix([[1,2],[3,4],[5,6]])
mat2 = Matrix([[1,4],[9,16],[25,36]])
mat1.vstack(mat2).numpy()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [26]:
mat1.vstack(mat2).numpy()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [27]:
mat1.hstack(mat2).numpy()

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16],
       [ 5,  6, 25, 36]])