# ***This notebook is only for testing***

In [1]:
from matrix import Matrix
import time


In [2]:
x = Matrix([[1,2,1],[0,1,0],[2,3,4]])
y = Matrix([[2,5],[6,7],[1,8]])

In [3]:
%%time
z = x @ y

CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
print(z.numpy())

[[15 27]
 [ 6  7]
 [26 63]]


In [5]:
test = [
  [1,2,3,0],
  [4,5,6,1],
  [4,5,6,1],
  [7,8,9,2]
]

matrix = Matrix(test)

In [6]:
matrix

<'Matrix' object at 0x1ba2fcf86d0 size=16 shape=(4, 4) symbol=None>

In [7]:
matrix.max_pooling((2,2)).numpy()

array([[5, 6, 6],
       [5, 6, 6],
       [8, 9, 9]])

In [8]:
%%time
matrix.argmax()

CPU times: total: 0 ns
Wall time: 0 ns


9

In [9]:
%%time
matrix.argmin()

CPU times: total: 0 ns
Wall time: 0 ns


0

In [10]:
from matrix import identity

In [11]:
identity(3).numpy()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
matrix.rand_like()

<'Matrix' object at 0x1ba2fba1250 size=16 shape=(4, 4) symbol=None>

In [13]:
matrix.zeros_like().numpy()

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
matrix.ones_like().numpy()

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [15]:
from torch import Tensor
import torch

In [16]:
x = Tensor([[1,2,3],[3,4,5],[6,7,8]])
y = Tensor([[1,4,9],[9,16,25],[36,49,64]])

In [17]:
z = torch.stack((x,y),dim = 0)

In [18]:
z

tensor([[[ 1.,  2.,  3.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.]],

        [[ 1.,  4.,  9.],
         [ 9., 16., 25.],
         [36., 49., 64.]]])

In [19]:
a = torch.stack((x,y),dim = 1)

In [20]:
a

tensor([[[ 1.,  2.,  3.],
         [ 1.,  4.,  9.]],

        [[ 3.,  4.,  5.],
         [ 9., 16., 25.]],

        [[ 6.,  7.,  8.],
         [36., 49., 64.]]])

In [21]:
p = torch.hstack((x,y))
p

tensor([[ 1.,  2.,  3.,  1.,  4.,  9.],
        [ 3.,  4.,  5.,  9., 16., 25.],
        [ 6.,  7.,  8., 36., 49., 64.]])

In [22]:
q = torch.vstack((x,y))
q

tensor([[ 1.,  2.,  3.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 1.,  4.,  9.],
        [ 9., 16., 25.],
        [36., 49., 64.]])

In [23]:
t1 = Tensor([[1,2],[3,4],[5,6]])
t2 = Tensor([[1,4],[9,16],[25,36]])
torch.vstack((t1,t2))

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 1.,  4.],
        [ 9., 16.],
        [25., 36.]])

In [24]:
torch.hstack((t1,t2))

tensor([[ 1.,  2.,  1.,  4.],
        [ 3.,  4.,  9., 16.],
        [ 5.,  6., 25., 36.]])

In [25]:
mat1 = Matrix([[1,2],[3,4],[5,6]])
mat2 = Matrix([[1,4],[9,16],[25,36]])
mat1.vstack(mat2).numpy()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [26]:
mat1.vstack(mat2).numpy()

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 1,  4],
       [ 9, 16],
       [25, 36]])

In [27]:
mat1.hstack(mat2).numpy()

array([[ 1,  2,  1,  4],
       [ 3,  4,  9, 16],
       [ 5,  6, 25, 36]])

In [28]:
mat1.mean()

3.5

In [29]:
from matrix import Matrix
import numpy as np

In [30]:
data = [[1,2,3],[4,5,6]]
mat = Matrix(data)
arr = np.array(data)

In [31]:
mat.numpy()

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
mat.var(sample = False),arr.var() # axis = None

(2.9166666666666665, 2.9166666666666665)

In [34]:
mat.var(axis = 1,sample = False).numpy(),arr.var(axis = 1)

(array([[0.66666667],
        [0.66666667]]),
 array([0.66666667, 0.66666667]))

In [35]:
mat.var(axis = 0,sample = False).numpy(),arr.var(axis = 0)

(array([[2.25],
        [2.25],
        [2.25]]),
 array([2.25, 2.25, 2.25]))

In [36]:
mat.var(axis = None,symbol = "A")

d:\fun\matrix-py\matrix\__init__.py:1028: UserWarning: Warning: the 'symbol' parameter is ignored when 'axis' is None.
  if symbol is not None: warnings.warn("Warning: the 'symbol' parameter is ignored when 'axis' is None.", UserWarning)


3.5

In [37]:
print(mat.std(axis = 1).numpy())
print(arr.std(axis = 1))

[[1.]
 [1.]]
[0.81649658 0.81649658]


In [38]:
mat.std(),mat.numpy()

(1.8708286933869707,
 array([[1, 2, 3],
        [4, 5, 6]]))

In [39]:
mat.std?

Signature: mat.std(axis=None, sample=True, symbol: Optional[str] = None)
Docstring: <no docstring>
File:      d:\fun\matrix-py\matrix\__init__.py
Type:      method

In [40]:
arr.var?

Docstring:
a.var(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)

Returns the variance of the array elements, along given axis.

Refer to `numpy.var` for full documentation.

See Also
--------
numpy.var : equivalent function
Type:      builtin_function_or_method

In [18]:
from matrix import Matrix
import matrix

In [19]:
rand = matrix.rand((3,3),42)

In [20]:
rand.sort(axis=None).numpy()

array([[0.05808361, 0.15599452, 0.15601864],
       [0.37454012, 0.59865848, 0.60111501],
       [0.73199394, 0.86617615, 0.95071431]])

In [21]:
rand.sort(axis=0).numpy()

array([[0.05808361, 0.15601864, 0.15599452],
       [0.37454012, 0.86617615, 0.60111501],
       [0.59865848, 0.95071431, 0.73199394]])

In [22]:
rand.sort(axis=1).numpy()

array([[0.37454012, 0.73199394, 0.95071431],
       [0.15599452, 0.15601864, 0.59865848],
       [0.05808361, 0.60111501, 0.86617615]])

In [23]:
r = Matrix([[1,2,3,4,5]])
r.numpy()

array([[1, 2, 3, 4, 5]])

In [24]:
r.is_row()

True

In [25]:
r.col

5

In [26]:
r.is_col()

False

In [27]:
matrix.arange(1,10).numpy()

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [28]:
matrix.arange(1,10,step = 1).numpy()

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [29]:
matrix.linspace(0,10,5,True).numpy()

array([[ 0. ,  2.5,  5. ,  7.5, 10. ]])

In [30]:
matrix.linspace(0,10,5,True,shape = (5,1)).numpy()

array([[ 0. ],
       [ 2.5],
       [ 5. ],
       [ 7.5],
       [10. ]])

In [31]:
matrix.linspace(0,10,5,True,shape = (5,1),symbol = "A")

KeyError: "'A' already exists! try with different symbol"

In [17]:
matrix.mem()

"A = <'Matrix' object at 0x7efdf59c3040 size=5 shape=(1, 5) symbol=A>\n"

In [15]:
matrix.linspace(0,10,5,True,symbol = "A")

KeyError: "'A' already exists! try with different symbol"

In [16]:
Matrix([[1,2,3],[4,5,6]],symbol = "B")

<'Matrix' object at 0x7f7e37c0e3b0 size=6 shape=(2, 3) symbol=B>

In [2]:
import matrix

In [3]:
matrix.linspace(0,10,2,symbol="A")

<'Matrix' object at 0x7f7aedcbdc60 size=2 shape=(1, 2) symbol=A>

In [4]:
from matrix import Matrix
import numpy as np

In [5]:
x = Matrix([[1,2,3],[4,5,6]])
y = np.array([[1,2,3],[4,5,6]])

In [6]:
def softmax_2d(Z, axis=1):
    # Subtracting the max for numerical stability
    Z = Z - np.max(Z, axis=axis, keepdims=True)
    exp_Z = np.exp(Z)
    return exp_Z / np.sum(exp_Z, axis=axis, keepdims=True)

In [7]:
x.softmax(axis=0).numpy(),softmax_2d(y,axis=0)

(array([[0.04742587, 0.04742587, 0.04742587],
        [0.95257413, 0.95257413, 0.95257413]]),
 array([[0.04742587, 0.04742587, 0.04742587],
        [0.95257413, 0.95257413, 0.95257413]]))

In [8]:
x.softmax(axis=1).numpy(),softmax_2d(y,axis=1)

(array([[0.09003057, 0.24472847, 0.66524096],
        [0.09003057, 0.24472847, 0.66524096]]),
 array([[0.09003057, 0.24472847, 0.66524096],
        [0.09003057, 0.24472847, 0.66524096]]))

In [9]:
import matrix as m
m.matrix?

Signature:
m.matrix(
    array1d: List[Union[int, float, bool]],
    shape: Tuple[int, int],
    symbol: Optional[str] = None,
)
Docstring: <no docstring>
File:      d:\fun\matrix-py\matrix\__init__.py
Type:      function