# ***This notebook is only for testing***

In [1]:
from matrix import Matrix
from torch import Tensor
import time

In [2]:
x = Matrix([[1,2,1],[0,1,0],[2,3,4]])
y = Matrix([[2,5],[6,7],[1,8]])

In [3]:
%%time
z = x @ y

CPU times: total: 0 ns
Wall time: 0 ns


In [4]:
print(z.numpy())

[[15 27]
 [ 6  7]
 [26 63]]


In [5]:
test = [
  [1,2,3,0],
  [4,5,6,1],
  [4,5,6,1],
  [7,8,9,2]
]

matrix = Matrix(test)

In [6]:
matrix

<'Matrix' object at 0x25cf1d3eb50 size=16 shape=(4, 4) symbol=None>

In [7]:
matrix.max_pooling((2,2)).numpy()

array([[5, 6, 6],
       [5, 6, 6],
       [8, 9, 9]])

In [8]:
%%time
matrix.argmax()

CPU times: total: 0 ns
Wall time: 0 ns


9

In [9]:
%%time
matrix.argmin()

CPU times: total: 0 ns
Wall time: 0 ns


0

In [10]:
from matrix import identity

In [12]:
identity(3).numpy()

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])